import pymysql

py = pymysql.connect(host='localhost', user='root', password='351172abc2015', port=3306, charset='utf8')
cursor = py.cursor()
cursor.execute("CREATE DATABASE IF NOT EXISTS shopsystem DEFAULT CHARACTER SET utf8")
# 进入数据库data_socket
dy = pymysql.connect(host='localhost', user='root', password='351172abc2015', port=3306, charset='utf8',
                     database='shopsystem')
cursor = dy.cursor()
cursor.execute('CREATE TABLE IF NOT EXISTS business_income (code varchar(50) unique primary key ,income varchar(200)) ')
cursor.execute('CREATE TABLE IF NOT EXISTS business_favor (code varchar(50) unique primary key ,favor varchar(200)) ')
cursor.execute('CREATE TABLE IF NOT EXISTS business_sale (code varchar(50) unique primary key ,sale varchar(200)) ')
cursor.execute('CREATE TABLE IF NOT EXISTS business_criticism (code varchar(50) unique primary key ,criticism varchar(200)) ')
cursor.execute('CREATE TABLE IF NOT EXISTS address (id varchar(50),address varchar(500))')
cursor.execute('CREATE TABLE IF NOT EXISTS comment (usercode varchar(50) ,text varchar(500),foodcode varchar(50))')
cursor.execute('CREATE TABLE IF NOT EXISTS user (code varchar(50) unique primary key ,name varchar(50),photo varchar(500) ,motto varchar(50))')
cursor.execute('CREATE TABLE IF NOT EXISTS food_order (business_id varchar(50),user_id varchar(50),rider_id varchar(50),food_id varchar(50),order_time varchar(100),order_statue varchar(50),order_number varchar(50),order_id varchar(50),order_address varchar(200),order_transactions varchar(50))')
# cursor.execute('select address from address where id="fbade9e36a3f36d3d676c1b808451dd7"')
# res=cursor.fetchall()
# print(res)
# print(res[0])
# print(res[0][0])
cursor.execute('CREATE TABLE IF NOT EXISTS talk_massage (massage varchar(1000) ,name varchar(50),photo varchar(500),time varchar(50),identity varchar(50) ,userdata varchar(50))')
cursor.execute('CREATE TABLE IF NOT EXISTS rider_income (code varchar(50) unique primary key ,income varchar(200)) ')
cursor.execute('CREATE TABLE IF NOT EXISTS rider_favor (code varchar(50) unique primary key ,favor varchar(200)) ')
cursor.execute('CREATE TABLE IF NOT EXISTS rider_send (code varchar(50) unique primary key ,send varchar(200)) ')
cursor.execute('CREATE TABLE IF NOT EXISTS rider_criticism (code varchar(50) unique primary key ,criticism varchar(200)) ')
cursor.execute('CREATE TABLE IF NOT EXISTS rider (code varchar(50) unique primary key ,name varchar(50),photo varchar(500) ,motto varchar(50))')